spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/audit
    driver-class-name: org.postgresql.Driver

javers:
  mappingStyle: FIELD
  algorithm: SIMPLE
  commitIdGenerator: synchronized_sequence
  prettyPrint: true
  typeSafeValues: false
  initialChanges: true
  terminalChanges: true
  packagesToScan:
  auditableAspectEnabled: true
  springDataAuditableRepositoryAspectEnabled: true
  prettyPrintDateFormats:
    localDateTime: 'dd MMM yyyy, HH:mm:ss'
    zonedDateTime: 'dd MMM yyyy, HH:mm:ssZ'
    localDate: 'dd MMM yyyy'
    localTime: 'HH:mm:ss'
  sqlSchema:
    sqlSchemaManagementEnabled: true
    sqlGlobalIdCacheDisabled: false
    objectAccessHook: org.javers.hibernate.integration.HibernateUnproxyObjectAccessHook
    sqlGlobalIdTableName: expert_global_id
    sqlCommitTableName: expert_commit
    sqlSnapshotTableName: expert_snapshot
    sqlCommitPropertyTableName: expert_commit_property
